# Generated by Django 3.2.6 on 2021-08-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0004_studentrecord_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='customer_address',
            new_name='address',
        ),
    ]
