# Generated by Django 3.2.6 on 2021-08-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0005_rename_customer_address_studentrecord_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelform.customerrecord1'),
        ),
    ]
